# Generated by Django 4.2.8 on 2023-12-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='hello/static/photos')),
                ('data', models.TextField()),
                ('org', models.TextField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('full_name', models.TextField()),
                ('gender', models.CharField()),
                ('type', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField()),
                ('direction', models.TextField()),
                ('event', models.TextField()),
                ('image', models.ImageField(upload_to='hello/static/photos')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
